# PCA

In [20]:
from datascience import *
from scipy import stats
import numpy as np
from numpy import linalg as la
import matplotlib
matplotlib.use('Agg', warn=False)
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [3]:
a = Table.read_table('pca_data.csv')

### calculating zero mean data

In [14]:
x_std = a.column('x')
y_std = a.column('y')
x_std-=np.mean(x_std)
y_std-=np.mean(y_std)
print(x_std)
print(y_std)

[ 0.69 -1.31  0.39  0.09  1.29  0.49  0.19 -0.81 -0.31 -0.71]
[ 0.49 -1.21  0.99  0.29  1.09  0.79 -0.31 -0.81 -0.31 -1.01]


### calculating covariance matrix

In [16]:
covariance = np.cov(x_std, y_std)
#covariance = np.asmatrix(covariance)

### calculating eigen values and eigen vectors

In [19]:
eigen_values, eigen_vectors = la.eig(covariance)
print(eigen_values)
print(eigen_vectors)

[0.0490834  1.28402771]
[[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]


### finding transpose of eigen vectors and zero mean data

In [23]:
transpose_ev = np.transpose(eigen_vectors)
transpose_ev

array([[-0.73517866,  0.6778734 ],
       [-0.6778734 , -0.73517866]])

In [46]:
temp = np.column_stack((x_std, y_std))
transpose_zm = np.transpose(temp)
transpose_zm

array([[ 0.69, -1.31,  0.39,  0.09,  1.29,  0.49,  0.19, -0.81, -0.31,
        -0.71],
       [ 0.49, -1.21,  0.99,  0.29,  1.09,  0.79, -0.31, -0.81, -0.31,
        -1.01]])

### multiplication of transpose matrices

In [49]:
result = np.dot(transpose_ev, transpose_zm)
finalx = result[1]
finaly = result[0]
answer = Table().with_columns(['x', finalx, 'y', finaly])
answer

x         | y
-0.82797  | -0.175115
1.77758   | 0.142857
-0.992197 | 0.384375
-0.27421  | 0.130417
-1.6758   | -0.209498
-0.912949 | 0.175282
0.0991094 | -0.349825
1.14457   | 0.0464173
0.438046  | 0.0177646
1.22382   | -0.162675